# Generated by Django 3.1.1 on 2020-10-16 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('ID_Equipo', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_Equipo', models.CharField(max_length=20)),
                ('Estado_Equipo', models.CharField(max_length=20)),
                ('Mascota_Equipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Equipo',
            },
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Jugador', models.IntegerField()),
                ('Nombre_Jugador', models.CharField(max_length=20)),
                ('Apellido_Jugador', models.CharField(max_length=20)),
                ('Nombre_Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.equipos')),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Estadios',
            fields=[
                ('ID_Estadio', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_Estadio', models.CharField(max_length=50)),
                ('Estado_Estadio', models.CharField(max_length=20)),
                ('Ciudad_Estadio', models.CharField(max_length=20)),
                ('Capacidad_Estadio', models.IntegerField()),
                ('Nombre_Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.equipos')),
            ],
            options={
                'verbose_name_plural': 'Estadios',
            },
        ),
    ]
